theme: jekyll-theme-slate
title: Fannie Vaquero's CV
description: <a href="https://drive.google.com/viewer?url=https://raw.githubusercontent.com/penguin64100/cv/pdf/penguin64100_CV.pdf">View PDF</a>
              &#124; <a href="https://raw.githubusercontent.com/penguin64100/cv/pdf/penguin64100_CV.pdf">Download PDF</a> 
              &#124; <a href="https://penguin64100.github.io/cv/resume_pdf.htm?src=https://raw.githubusercontent.com/penguin64100/cv/main/index.md">View Markdown</a>
github:
  is_project_page: false
